### ISSUE TITLE
Rosbag to PointCLoud

### ISSUE THREAD

**Issue by ManChrys** [Livox-SDK/livox_ros_driver#95]
hello,

i would like to ask you how can i convert rosbag to a ply format for example las,laz,ply

i saw that page http://wiki.ros.org/pcl_ros#pointcloud_to_pcd but when im converting bag to pcd it creates a lot of pcds and not one pcd. It is one pcd for every frame. 

Any suggestions ? Thanks in advance.

**Comment by Livox-SDK** [comment]
Hi ManChrys,

There is a part of code for saving the pointcloud as pcd in the code livox_mapping which can be refered:
![64D1A6C0-CADC-2FBA-EAC8-C2A75B879D22](https://user-images.githubusercontent.com/45850995/126738082-2229fba2-d9fe-41e0-ab40-bb97b1e2d318.png)

**Comment by ManChrys** [comment]
Ok I see.

Thank you a lot.

**Comment by ManChrys** [comment]
hello,

i tried livox mapping and the result of pcd has big difference compared to bag file. Is there something else to try ? I have to convert it to a common pointcloud format like ply, las, laz so i can import them to point cloud softwares like cloudcompare. 

livox_mapping pcd:

![Screenshot from 2021-07-24 21-20-54](https://user-images.githubusercontent.com/67521662/126877828-9c4a115f-a31a-423d-bf2f-1707ea5429b1.png)

rosbag (converted from .lvx file)

![Screenshot from 2021-07-24 21-28-02](https://user-images.githubusercontent.com/67521662/126877986-344b9383-d7fb-4909-bd21-df62721e0426.png)

**Comment by Martinyllim** [comment]
bag_to_pcd from pcl_ros is built to dump one PCD per frame since it's just writing out each PointCloud2 message as it comes, it's not doing any registration or accumulation between frames, so that behavior is expected rather than a bug. To get one unified cloud (and LAS/LAZ/PLY from there) you need something doing scan matching or SLAM to merge the frames into a common reference frame first, then you can export the merged result in whatever format you want. pcl_ros's concatenate_and_downsample node can crudely stack the individual PCDs into one file if the platform barely moved, but if there's any real motion in your recording you'll get ghosting and doubled geometry without actual registration between scans.

If you're looking for something that handles the registration step, GLIM or FAST-LIO2 are common picks for Livox specifically. Full disclosure, I built a browser tool called LidarFlow that runs GLIM on a rosbag or MCAP and hands back PCD, PLY, and LAZ from the merged result, might save you standing up the SLAM pipeline yourself if you just want the output.
